<a href="https://colab.research.google.com/github/utkarsh0702/Pytorch/blob/master/Pytorch1_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
x= torch.tensor([3,5])
y= torch.tensor([2,1])
x*y

tensor([6, 5])

In [3]:
x= torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y= torch.rand([2,5])
y

tensor([[0.4714, 0.0534, 0.5857, 0.4386, 0.7475],
        [0.2070, 0.4133, 0.7433, 0.0864, 0.2503]])

In [6]:
#Reshaping the data array in pytorch
y= y.view([1,10])
y

tensor([[0.4714, 0.0534, 0.5857, 0.4386, 0.7475, 0.2070, 0.4133, 0.7433, 0.0864,
         0.2503]])

In [7]:
y= y.view([5,2])
y

tensor([[0.4714, 0.0534],
        [0.5857, 0.4386],
        [0.7475, 0.2070],
        [0.4133, 0.7433],
        [0.0864, 0.2503]])